import 'fake-indexeddb/auto'

import { afterAll, beforeEach, describe, expect, it, vi } from 'vitest'

const syncStub = vi.hoisted(() => ({
  syncCurrentSessionIfOnline: vi.fn().mockResolvedValue(undefined),
}))

vi.mock('../../infrastructure/sync/sync', () => syncStub)

import {
  getVehicleState,
  listFuelEntries,
  listOdometerReadings,
} from '../../infrastructure/local/store'
import { resetLocalDatabase } from '../../infrastructure/local/db'
import {
  initializeVehicle,
  recordFuel,
  recordOdometer,
} from './vehicleActions'

const initialAt = '2026-09-29T10:00:00.000Z'
const laterAt = '2026-09-30T10:00:00.000Z'
const randomUUID = vi.spyOn(globalThis.crypto, 'randomUUID')

function nextUuid(sequence: number): ReturnType<Crypto['randomUUID']> {
  return `00000000-0000-4000-8000-${String(sequence).padStart(12, '0')}`
}

describe('vehicle actions', () => {
  let sequence = 0

  beforeEach(async () => {
    await resetLocalDatabase()
    syncStub.syncCurrentSessionIfOnline.mockClear()
    sequence = 0
    randomUUID.mockImplementation(() => nextUuid(++sequence))
  })

  afterAll(async () => {
    randomUUID.mockRestore()
    await resetLocalDatabase()
  })

  it('initializes the vehicle with the configured tank capacity', async () => {
    await initializeVehicle(1_000, initialAt)

    await expect(getVehicleState()).resolves.toMatchObject({
      tankCapacityLiters: 3,
      initialOdometerKm: 1_000,
      initialFullTankAt: initialAt,
      createdAt: initialAt,
      updatedAt: initialAt,
    })
    expect(syncStub.syncCurrentSessionIfOnline).toHaveBeenCalledOnce()
  })

  it('creates the initial manual odometer reading', async () => {
    await initializeVehicle(1_000, initialAt)

    await expect(listOdometerReadings()).resolves.toEqual([
      expect.objectContaining({
        readingKm: 1_000,
        recordedAt: initialAt,
        source: 'manual',
        syncStatus: 'pending',
      }),
    ])
  })

  it('rolls back vehicle state when the initial reading cannot be written', async () => {
    randomUUID.mockReturnValueOnce(
      undefined as unknown as ReturnType<Crypto['randomUUID']>,
    )

    await expect(initializeVehicle(1_000, initialAt)).rejects.toBeDefined()
    await expect(getVehicleState()).resolves.toBeNull()
    await expect(listOdometerReadings()).resolves.toEqual([])
  })

  it('rejects a negative initial odometer', async () => {
    await expect(initializeVehicle(-1, initialAt)).rejects.toBeInstanceOf(
      RangeError,
    )
    await expect(getVehicleState()).resolves.toBeNull()
  })

  it('saves a normal odometer reading', async () => {
    await initializeVehicle(1_000, initialAt)

    await expect(recordOdometer(1_100, laterAt)).resolves.toEqual({
      kind: 'saved',
    })
    await expect(listOdometerReadings()).resolves.toHaveLength(2)
    expect(syncStub.syncCurrentSessionIfOnline).toHaveBeenCalledTimes(2)
  })

  it('does not write an odometer regression', async () => {
    await initializeVehicle(1_000, initialAt)

    await expect(recordOdometer(999.9, laterAt)).resolves.toMatchObject({
      kind: 'invalid',
    })
    await expect(listOdometerReadings()).resolves.toHaveLength(1)
  })

  it('requires confirmation before a suspicious odometer jump', async () => {
    await initializeVehicle(1_000, initialAt)

    const result = await recordOdometer(1_500.1, laterAt)

    expect(result.kind).toBe('requires_confirmation')
    expect(result.kind === 'requires_confirmation' && result.deltaKm)
      .toBeCloseTo(500.1)
    await expect(listOdometerReadings()).resolves.toHaveLength(1)
  })

  it('saves a confirmed suspicious odometer jump', async () => {
    await initializeVehicle(1_000, initialAt)

    await expect(recordOdometer(1_500.1, laterAt, true)).resolves.toEqual({
      kind: 'saved',
    })
    await expect(listOdometerReadings()).resolves.toHaveLength(2)
  })

  it('saves a valid fuel entry and matching odometer reading', async () => {
    await initializeVehicle(1_000, initialAt)

    await expect(
      recordFuel({
        odometerKm: 1_100,
        amountCents: 2_590,
        liters: 1.5,
        fullTank: false,
        fueledAt: laterAt,
      }),
    ).resolves.toEqual({ kind: 'saved' })

    await expect(listFuelEntries()).resolves.toEqual([
      expect.objectContaining({
        odometerKm: 1_100,
        amountCents: 2_590,
        liters: 1.5,
        fullTank: false,
        syncStatus: 'pending',
      }),
    ])
    await expect(listOdometerReadings()).resolves.toHaveLength(2)
    expect(syncStub.syncCurrentSessionIfOnline).toHaveBeenCalledTimes(2)
  })

  it('marks the odometer reading generated by fuel as fuel_entry', async () => {
    await initializeVehicle(1_000, initialAt)
    await recordFuel({
      odometerKm: 1_100,
      amountCents: 2_590,
      liters: 1.5,
      fullTank: true,
      fueledAt: laterAt,
    })

    expect(await listOdometerReadings()).toContainEqual(
      expect.objectContaining({
        readingKm: 1_100,
        recordedAt: laterAt,
        source: 'fuel_entry',
      }),
    )
  })

  it('commits the fuel entry and reading together', async () => {
    await initializeVehicle(1_000, initialAt)
    await recordFuel({
      odometerKm: 1_100,
      amountCents: 2_590,
      liters: 1.5,
      fullTank: true,
      fueledAt: laterAt,
    })

    await expect(listFuelEntries()).resolves.toHaveLength(1)
    await expect(listOdometerReadings()).resolves.toHaveLength(2)
  })

  it.each([0, -1])('rejects amountCents=%s', async (amountCents) => {
    await expect(
      recordFuel({
        odometerKm: 1_000,
        amountCents,
        liters: 1,
        fullTank: false,
        fueledAt: laterAt,
      }),
    ).resolves.toMatchObject({ kind: 'invalid' })
    await expect(listFuelEntries()).resolves.toEqual([])
  })

  it('rejects a non-integer amount in cents', async () => {
    await expect(
      recordFuel({
        odometerKm: 1_000,
        amountCents: 10.5,
        liters: 1,
        fullTank: false,
        fueledAt: laterAt,
      }),
    ).resolves.toMatchObject({ kind: 'invalid' })
    await expect(listFuelEntries()).resolves.toEqual([])
  })

  it.each([0, -1])('rejects liters=%s', async (liters) => {
    await expect(
      recordFuel({
        odometerKm: 1_000,
        amountCents: 1_000,
        liters,
        fullTank: false,
        fueledAt: laterAt,
      }),
    ).resolves.toMatchObject({ kind: 'invalid' })
    await expect(listFuelEntries()).resolves.toEqual([])
  })

  it('rejects a regressive fuel odometer without writing', async () => {
    await initializeVehicle(1_000, initialAt)

    await expect(
      recordFuel({
        odometerKm: 999,
        amountCents: 1_000,
        liters: 1,
        fullTank: false,
        fueledAt: laterAt,
      }),
    ).resolves.toMatchObject({ kind: 'invalid' })
    await expect(listFuelEntries()).resolves.toEqual([])
    await expect(listOdometerReadings()).resolves.toHaveLength(1)
  })

  it('requires confirmation for a suspicious fuel odometer', async () => {
    await initializeVehicle(1_000, initialAt)

    const result = await recordFuel({
      odometerKm: 1_500.1,
      amountCents: 1_000,
      liters: 1,
      fullTank: false,
      fueledAt: laterAt,
    })

    expect(result.kind).toBe('requires_confirmation')
    expect(result.kind === 'requires_confirmation' && result.deltaKm)
      .toBeCloseTo(500.1)
    await expect(listFuelEntries()).resolves.toEqual([])
    await expect(listOdometerReadings()).resolves.toHaveLength(1)
  })

  it('does not report success when the fuel transaction fails', async () => {
    await initializeVehicle(1_000, initialAt)
    randomUUID
      .mockReturnValueOnce(nextUuid(100))
      .mockReturnValueOnce(
        undefined as unknown as ReturnType<Crypto['randomUUID']>,
      )

    await expect(
      recordFuel({
        odometerKm: 1_100,
        amountCents: 1_000,
        liters: 1,
        fullTank: false,
        fueledAt: laterAt,
      }),
    ).rejects.toBeDefined()
    await expect(listFuelEntries()).resolves.toEqual([])
    await expect(listOdometerReadings()).resolves.toHaveLength(1)
  })

  it('rejects malformed fuel values before persistence', async () => {
    await expect(
      recordFuel({
        odometerKm: Number.NaN,
        amountCents: 1_000,
        liters: 1,
        fullTank: false,
        fueledAt: 'not-a-date',
      }),
    ).resolves.toMatchObject({ kind: 'invalid' })
    await expect(listFuelEntries()).resolves.toEqual([])
  })
})
